services:
  - type: web
    name: videasy-resolver
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: TMDB_API_KEY
        sync: false
